# baseURL = "https://vielmetti.github.io/commonplace/"
languageCode = "en-us"
title = "Works on Arm Cluster"
theme = "docdock2"
relativeURLs = true

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[params]
   themeStyle = "original"
   editURL = "https://github.com/worksonarm/cluster/tree/master/content/"
